### ISSUE TITLE
How to avoid npm WARN saveError ENOENT: no such file or directory, open 'npcheck-env/package.json'

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/npcheck#8]
I'm not 100% sure if I'm missing something but I created a `npcheck.json` file inside a new directory with the following content:

```
{
  "modules": [
    {
      "name": "kafkajs",
      "npmLink": "https://www.npmjs.com/package/kafkajs"
    }
  ],
  "licenses": {
    "allow": ["MIT", "Apache-2.0"]
  }
}
```

After run npcheck, it shows the following output:

```
Running checks on kafkajs

Checking if it's deprecated on NPM PASS
Checking if github repository is archived PASS

Checking top-level license PASS

Downloading module dependencies...
npm WARN saveError ENOENT: no such file or directory, open '/home/hf/code/foo/npcheck-env/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/hf/code/foo/npcheck-env/package.json'
npm WARN npcheck-env No description
npm WARN npcheck-env No repository field.
npm WARN npcheck-env No README data
npm WARN npcheck-env No license field.

+ kafkajs@1.15.0
added 1 package from 1 contributor and audited 1 package in 1.104s
found 0 vulnerabilities

 

Checking if module has appropriate testing PASS

Checking maintenance metrics PASS

NPCheck Report

problems: 0 (errors: 0 - warnings: 0)
```

**Comment by alexalikiotis** [comment]
@helio-frota Let me clarify why you're seeing these warnings.

The warnings are generated by the npm CLI that npcheck uses under the hood to download all of the dependencies of a module. Now because this process is one-off (meaning download deps -> license check -> remove deps) we don't create the package.json or the package-lock.json files. (because we don't need them in this case).

But in the end, the under-the-hood npm CLI can't find the package.json file and that's why it warns us. The warnings are completely fine and expected and do not have any impact on npcheck's functionality.

**Comment by helio-frota** [comment]
@alexalikiotis thanks for the information.
In that case makes sense npcheck to pass a `--silent` option to NPM ?

**Comment by alexalikiotis** [comment]
@helio-frota sounds good to me! I'll leave this issue open so I won't forget to add the `--silent` command.
